version: "1"

services:

  node:
    container_name: node-cloud
    image: node:iron-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - ${NODE_REACT_PORT}:3030
    command: sleep infinity

  python:
    container_name: python-cloud
    image: python:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - ${PYTHON_DJANGO_PORT}:3020
    command: sleep infinity

  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}