version: "1.1"

services:

  node:
    container_name: node-cloud
    image: node:iron-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - ${NODE_REACT_PORT}:3030
    command: sleep infinity

  python:
    container_name: python-cloud
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - ${PYTHON_DJANGO_PORT}:3020
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_HOST: "postgresql"
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command:
      sh -c "python cloud_dev/manage.py makemigrations &&
             python cloud_dev/manage.py migrate &&
             python cloud_dev/manage.py runserver 0.0.0.0:3020"
    depends_on:
      - postgresql
      - redis

  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379